version: '3'
volumes:
  data:
services:
  db:
    container_name: todo
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"