### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json
{
    "title": "task 2",
    "date": "2021-01-01",
    "description": "description of task 2",
    "priority": "normal",
    "status": "todo"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json
{
    "id": "d0568277-57fa-4805-86b7-c22e7f3c9aa5",
    "status": "inProgress"
}